### ISSUE TITLE
精确覆盖率TOP指标分析

### ISSUE THREAD

**Issue by ouyh18** [ouyh18/LtePlatform#2]
开始用AngularJS呈现精确覆盖率TOP指标

**Comment by ouyh18** [comment]
完成TOP指标的呈现，但未完成辅助功能（如加入监控、地理化显示等）

**Comment by ouyh18ctc** [comment]
完成TOP小区及其邻区的监控增加管理功能。

**Comment by ouyh18ctc** [comment]
开始干扰分析页面：
`<div uib-alert ng-repeat="message in updateMessages" type="success" dismiss-on-timeout="2000" close="closeAlert($index)">
    {{message.cellName}}更新干扰小区信息{{message.counts}}条
</div>
<div uib-accordion close-others="oneAtATime">
    <div uib-accordion-group heading="干扰源分析" panel-class="panel-warning">
        <div ng-include="'/appViews/Rutrace/Interference/Source.html'"></div>
    </div>
    <div uib-accordion-group heading="被干扰小区" panel-class="panel-success">
        <div ng-include="'/appViews/Rutrace/Interference/Victim.html'"></div>
    </div>
</div>`

**Comment by ouyh18ctc** [comment]
路由选择：
`var cell = $scope.topStat.current;
    if (cell.eNodebName === undefined || cell.eNodebName === "")
        $location.path($scope.rootPath + "top");
    else {
        $scope.showInterference();
    }`

**Comment by ouyh18ctc** [comment]
TypeError: Cannot read property 'value' of undefined
    at Scope.$scope.showInterference
`$http({
                method: 'GET',
                url: appUrlService.getApiUrl('InterferenceNeighbor'),
                params: {
                    'begin': $scope.beginDate.value,
                    'end': $scope.endDate.value,
                    'cellId': cell.cellId,
                    'sectorId': cell.sectorId
                },
                headers: {
                    'Authorization': 'Bearer ' + appUrlService.getAccessToken()
                }
            }).success(function (result) {
                $scope.interferenceCells = result;
            });`
